
---
- name: Task Install zabbix-agent2 and set environment
  hosts: all
  become: true
  tasks:
    - name: Download Zabbix Agent 2 RPM
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-agent2-6.0.0-1.el8.x86_64.rpm"
        dest: "/tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm"

    - name: Install package rpm
      ansible.builtin.command: dnf install -y /tmp/zabbix-agent2-6.0.0-1.el8.x86_64.rpm
      ignore_errors: true

    - name: Replace host IP in zabbix-agent2.conf
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Hostname\s*=\s*.*$'
        line: 'Hostname = {{ inventory_hostname }}'  # Replace with the new IP address

    - name: Allow all ip to connect to zabbix-agent2
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server\s*=\s*.*$'
        line: 'Server=0.0.0.0/0'  # Replace with the new IP address

    - name: Start service zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        state: started

    - name: Enable service zabbix-agent2
      ansible.builtin.service:
        name: zabbix-agent2
        enabled: true